name: Build/release Electron app

on:
  push:
    branches:
      - feature/cicd
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Check Environment Variables
        run: echo "GH_TOKEN=${{ secrets.GH_TOKEN }}"
        shell: bash


      - name: build-linux
        if: matrix.os == 'ubuntu-latest'
        run:GH_TOKEN=${{ secrets.GH_TOKEN }} npm run build:linux

      - name: build-mac
        if: matrix.os == 'macos-latest'
        run: GH_TOKEN=${{ secrets.GH_TOKEN }} npm run build:mac

      - name: build-win
        if: matrix.os == 'windows-latest'
        run: GH_TOKEN=${{ secrets.GH_TOKEN }} npm run build:win

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            dist/*.exe
            dist/*.zip
            dist/*.dmg
            dist/*.AppImage
            dist/*.snap
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/*.yml
            dist/*.blockmap
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
